# Generated by Django 5.0.3 on 2024-03-25 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='origination',
            new_name='origination_city',
        ),
        migrations.AddField(
            model_name='person',
            name='email',
            field=models.EmailField(default='', max_length=64),
        ),
        migrations.AddField(
            model_name='person',
            name='last_name',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AddField(
            model_name='person',
            name='origination_state',
            field=models.CharField(default='', max_length=2),
        ),
        migrations.AddField(
            model_name='person',
            name='service_type',
            field=models.CharField(choices=[('regular', 'Regular CartyCity'), ('premium', 'Premium CartyCity')], default='regular', max_length=10),
        ),
        migrations.AddField(
            model_name='person',
            name='vehicle_type',
            field=models.CharField(default='', max_length=64),
        ),
    ]
